if not minetest.global_exists("unified_inventory") then return end

local group_images = {
	-- choppy             = "3d_armor_stand:armor_stand",
	-- cracky             = "areasprotector:protector_large",
	-- crumbly            = "aqua_farming:water_soil",
	-- snappy             = "artdeco:irongrating",
	-- dig_immediate      = "aqua_farming:alga_seed",
	-- oddly_breakable_by_hand = "3d_armor_stand:armor_stand",

	axe                = "default:axe_diamond",
	hoe                = "farming:hoe_diamond",
	pickaxe            = "default:pick_diamond",
	shovel             = "default:shovel_diamond",
	sword              = "default:sword_diamond",

	armor_feet         = "3d_armor:boots_diamond",
	armor_fire         = "terumet:brcr_fire",
	armor_head         = "3d_armor:helmet_diamond",
	armor_heal         = "terumet:brcr_heal",
	armor_legs         = "3d_armor:leggings_diamond",
	armor_shield       = "shields:shield_diamond",
	armor_torso        = "3d_armor:chestplate_diamond",
	-- armor_use          = "3d_armor:boots_bronze",
	armor_water        = "terumet:brcr_aqua",

	_terumetal_battery = "terumet:item_batt_therm",
	armor_terumet_brcr = "terumet:brcr_base",
	attached_node      = "xdecor:painting_1",
	bagslots           = "unified_inventory:bag_large",
	bakedclay          = "bakedclay:natural",
	bed                = "beds:bed_bottom",
	-- bendy              = "mesecons_delayer:delayer_off_1",
	bone               = "bonemeal:bone",
	book               = "default:book",
	bouncy             = "xdecor:trampoline",
	bread_dough        = "cucina_vegana:ciabatta_dough",
	bush               = "bushes:blackberry_bush",
	carpet             = "baldcypress:dry_branches",
	catchable          = "butterflies:butterfly_red",
	chainlinks         = "basic_materials:chainlink_brass",
	coal               = "default:coal_lump",
	color_black        = "dye:black",
	color_blue         = "dye:blue",
	color_brown        = "dye:brown",
	color_cyan         = "dye:cyan",
	color_dark_green   = "dye:dark_green",
	color_dark_grey    = "dye:dark_grey",
	color_green        = "dye:green",
	color_grey         = "dye:grey",
	color_magenta      = "dye:magenta",
	color_orange       = "dye:orange",
	color_pink         = "dye:pink",
	color_red          = "dye:red",
	color_violet       = "dye:violet",
	color_white        = "dye:white",
	color_yellow       = "dye:yellow",
	concrete           = "basic_materials:concrete_block",
	concrete_post      = "technic:concrete_post",
	connect_to_raillike= "boost_cart:startstoprail",
	cools_lava         = "default:ice",
	detector_rail      = "boost_cart:detectorrail",
	digiline_receiver  = "digistuff:button",
	disable_jump       = "terumet:block_tar",
	disable_repair     = "orienteering:altimeter",
	disable_suffocation= "mobs:beehive",
	display_api        = "digiterms:cathodic_white_monitor",
	door               = "doors:slide_door",
	drink              = "farming:coffee_cup",
	dry_grass          = "default:dry_grass_1",
	dye                = "dye:violet",
	eatable            = "cucina_vegana:ciabatta_bread",
	elevator           = "travelnet:elevator",
	explody            = "bbq:propane",
	fall_damage_add_percent = "farming:straw",
	falling_node       = "default:gravel",
	feather            = "mobs:chicken_feather",
	fence              = "default:fence_wood",
	fern               = "default:fern_1",
	fire               = "fire:permanent_flame",
	flammable          = "default:tree",
	fleshy             = "plumtree:plum",
	flora              = "moreplants:medflower",
	flora_block        = "poisonivy:climbing",
	flow_through       = "ropes:ladder_steel",
	flower             = "rainf:dahlia",
	food               = "bbq:bacon_cheeseburger",
	food_apple         = "default:apple",
	food_baking_tray   = "farming:baking_tray",
	food_barberries    = "swaz:barberries",
	food_barley        = "farming:barley",
	food_beans         = "farming:beans",
	food_beetroot      = "farming:beetroot",
	food_berry         = "farming:blueberries",
	food_bird          = "cucina_vegana:imitation_poultry",
	food_blackberries  = "farming:blackberry",
	food_blackberry    = "farming:blackberry",
	food_blueberries   = "farming:blueberries",
	food_blueberry     = "bushes:blueberry",
	food_bowl          = "cucina_vegana:bowl",
	food_bread         = "farming:bread",
	food_bread_slice   = "farming:bread_slice",
	food_butter        = "mobs:butter",
	food_cabbage       = "farming:cabbage",
	food_carrot        = "farming:carrot",
	food_cheese        = "mobs:cheese",
	food_chicken       = "mobs:chicken_cooked",
	food_chicken_raw   = "mobs:chicken_raw",
	food_chili_pepper  = "farming:chili_pepper",
	food_cocoa         = "farming:cocoa_beans",
	food_coffee        = "farming:coffee_beans",
	food_corn          = "farming:corn",
	food_corn_cooked   = "farming:corn_cob",
	food_cornstarch    = "farming:cornstarch",
	food_cucumber      = "farming:cucumber",
	food_cutting_board = "farming:cutting_board",
	food_egg           = "mobs:egg",
	food_egg_fried     = "mobs:chicken_egg_fried",
	food_fish          = "mobs_fish:clownfish",
	food_flour         = "farming:flour",
	food_fruit         = "clementinetree:clementine",
	food_garlic        = "farming:garlic",
	food_garlic_clove  = "farming:garlic_clove",
	food_gelatin       = "bonemeal:gelatin_powder",
	food_gooseberry    = "bushes:gooseberry",
	food_grapes        = "farming:grapes",
	food_honey         = "mobs:honey",
	food_juicer        = "farming:juicer",
	food_lemon         = "lemontree:lemon",
	food_lettuce       = "farming:lettuce",
	food_meat          = "mobs:meat",
	food_meat_raw      = "mobs:meat_raw",
	food_melon         = "farming:melon_8",
	food_melon_slice   = "farming:melon_slice",
	food_milk          = "cucina_vegana:soy_milk",
	food_milk_glass    = "mobs:glass_milk",
	food_mint          = "farming:mint_leaf",
	food_mixing_bowl   = "farming:mixing_bowl",
	food_mortar_pestle = "farming:mortar_pestle",
	food_mushroom      = "flowers:mushroom_brown",
	food_mutton        = "mobs:mutton_cooked",
	food_mutton_raw    = "mobs:mutton_raw",
	food_oats          = "farming:oat",
	food_oil           = "extra:cottonseed_oil",
	food_onion         = "farming:onion",
	food_orange        = "clementinetree:clementine",
	food_pasta         = "farming:pasta",
	food_pea_pod       = "farming:pea_pod",
	food_peas          = "farming:peas",
	food_pepper        = "farming:pepper",
	food_pepper_ground = "farming:pepper_ground",
	food_peppercorn    = "farming:peppercorn",
	food_pineapple     = "farming:pineapple",
	food_pineapple_ring= "farming:pineapple_ring",
	food_plate         = "cucina_vegana:plate",
	food_poison        = "flowers:mushroom_red",
	food_pork          = "mobs:pork_cooked",
	food_pork_raw      = "mobs:pork_raw",
	food_pot           = "farming:pot",
	food_potato        = "farming:potato",
	food_pumpkin       = "farming:pumpkin_8",
	food_pumpkin_slice = "farming:pumpkin_slice",
	food_rabbit        = "mobs:rabbit_cooked",
	food_rabbit_raw    = "mobs:rabbit_raw",
	food_raspberries   = "farming:raspberries",
	food_raspberry     = "farming:raspberries",
	food_rat           = "mobs:rat_cooked",
	food_rhubarb       = "farming:rhubarb",
	food_rice          = "cucina_vegana:bowl_rice_cooked",
	food_rice_bread    = "farming:rice_bread",
	food_rice_flour    = "farming:rice_flour",
	food_rice_raw      = "cucina_vegana:rice",
	food_rose_water    = "farming:rose_water",
	food_rye           = "farming:rye",
	food_salt          = "farming:salt",
	food_sauce         = "cucina_vegana:sauce_hollandaise",
	food_saucepan      = "farming:saucepan",
	food_skillet       = "farming:skillet",
	food_soup          = "cucina_vegana:soy_soup",
	food_soy           = "farming:soy_beans",
	food_soy_pod       = "farming:soy_pod",
	food_starch        = "cucina_vegana:rice_starch",
	food_strawberry    = "aqua_farming:sea_strawberry_item",
	food_sugar         = "bbq:sugar",
	food_sweet         = "aqua_farming:sea_strawberry_cake_piece",
	food_toast         = "farming:toast",
	food_tofu          = "farming:tofu",
	food_tomato        = "farming:tomato",
	food_tomato_sauce  = "bbq:tomato_sauce",
	food_vanilla       = "farming:vanilla",
	food_vegan         = "aqua_farming:asparagus_rice",
	food_vinegarmother = "bbq:vinegar_mother",
	food_wheat         = "farming:wheat",
	fuel               = "scifi_nodes:crate",
	glue               = "terumet:item_glue",
	grass              = "default:grass_1",
	-- handy              = "morelights:chain_d",
	hay                = "cottages:hay_bale",
	horsetail          = "ferns:horsetail_04",
	hot                = "caverealms:hot_cobble",
	igniter            = "fire:permanent_flame",
	ingot              = "terumet:ingot_cgls",
	instrument         = "soundblocks:trumpet",
	junglegrass        = "default:junglegrass",
	large_banner       = "signs_road:large_street_sign_magenta",
	lava               = "default:lava_source",
	leafdecay          = "moretrees:jungletree_leaves_red",
	leafdecay_drop     = "cherrytree:cherries",
	leather            = "mobs:leather",
	leaves             = "default:leaves",
	-- level              = "basic_materials:brass_block",
	liquid             = "default:river_water_source",
	lump               = "terumet:lump_raw",
	marble             = "bls:marble",
	marram_grass       = "default:marram_grass_1",
	melty              = "moreores:mithril_block",
	mesecon            = "mesecons_extrawires:crossover_off",
	mesecon_conductor_craftable = "mesecons:wire_00000000_off",
	mesecon_effector_off = "mesecons_commandblock:commandblock_off",
	mesecon_needs_receiver = "homedecor:light_switch_off",
	mesecon_receptor_off = "mesecons_lamp:lamp_off",
	minegeld           = "currency:minegeld",
	minegeld_coin      = "currency:minegeld_cent_10",
	minegeld_note      = "currency:minegeld",
	moretrees_coconut  = "moretrees:coconut_3",
	moretrees_dates    = "moretrees:dates_f4",
	moretrees_leaves   = "moretrees:apple_tree_leaves",
	mounted_ceiling    = "morelights:chain_l",
	mushroom           = "flowers:mushroom_brown",
	nametag            = "mobs:nametag",
	node               = "doors:door_birch_wood",
	normal_grass       = "default:grass_1",
	not_blocking_trains= "signs_road:red_right_sign",
	nsspf_mushroom     = "nsspf:amanita_muscaria",
	overheat           = "mesecons_fpga:fpga0000",
	pane               = "xpanes:pane_flat",
	pebble             = "cavestuff:pebble_1",
	pelt               = "mobs:rabbit_hide",
	physics_gravity    = "terumet:armchest_cgls",
	physics_jump       = "terumet:brcr_jump",
	physics_speed      = "terumet:brcr_spd",
	pizza_dough        = "cucina_vegana:pizza_dough",
	plant              = "xdecor:ivy",
	poisonivy          = "poisonivy:sproutling",
	potting_soil       = "homedecor:flower_pot_terracotta",
	puts_out_fire      = "xdecor:packed_ice",
	radioactive        = "technic:mineral_uranium",
	rail               = "carts:rail",
	rope               = "xdecor:rope",
	rope_block         = "ropes:copper1rope_block",
	saddle             = "mobs:saddle",
	sand               = "default:sand",
	sapling            = "default:sapling",
	seafood            = "aqua_farming:sea_anemone_item",
	seed               = "farming:seed_wheat",
	seed_flax          = "cucina_vegana:flax_seed",
	seed_lettuce       = "cucina_vegana:lettuce_seed",
	seed_peanut        = "cucina_vegana:peanut_seed",
	seed_soy           = "cucina_vegana:soy_seed",
	slab               = "stairs:slab_clay",
	slippery           = "caverealms:thin_ice",
	snowy              = "default:snowblock",
	soil               = "default:dirt",
	spawn_egg          = "mob_horse:horse",
	spreading_dirt_type= "default:dirt_with_coniferous_litter",
	stair              = "stairs:stair_clay",
	stick              = "default:stick",
	stone              = "default:stone",
	string             = "cucina_vegana:flax_roasted",
	strip              = "basic_materials:copper_strip",
	sud                = "cucina_vegana:blueberry_pot",
	tar_block          = "building_blocks:Tar",
	terumet_hline      = "terumet:xfer_hline",
	terumet_hltarget   = "terumet:mach_asmelt",
	tnt                = "tnt:tnt",
	tool               = "screwdriver:screwdriver",
	torch              = "default:torch",
	travelnet          = "travelnet:travelnet",
	tree               = "default:tree",
	tubedevice         = "currency:shop",
	tubedevice_receiver= "currency:shop",
	ud_param2_colorable= "homedecor:armchair",
	uranium_block      = "technic:uranium_block",
	uranium_ingot      = "technic:uranium_ingot",
	vertical_digiline  = "digistuff:vertical_bottom",
	vessel             = "vessels:glass_bottle",
	vines              = "vines:vines",
	wall               = "terumet:wall_con_white",
	water              = "default:water_source",
	water_bucket       = "bucket:bucket_water",
	wet                = "scifi_nodes:pot2",
	wire               = "basic_materials:copper_wire",
	wood               = "default:wood",
	wool               = "wool:white",
}

for groupname, itemname in pairs(group_images) do
	unified_inventory.register_group_item(groupname, itemname)
end


--[[
-- Check for group image connflicts
for group, item in pairs(group_images) do
	for other_group, other_item in pairs(group_images) do
		if group ~= other_group and item == other_item then
			minetest.log("error", ("Group: %s conflicts with %s. Item: %s"):format(group, other_group, item))
		end
	end
end
]]


--[[
-- All groups, generated by another script, comprehensive
local all_groups = {
	"_terumetal_battery",
	"armor_feet",
	"armor_fire",
	"armor_head",
	"armor_heal",
	"armor_legs",
	"armor_shield",
	"armor_terumet_brcr",
	"armor_torso",
	"armor_use",
	"armor_water",
	"attached_node",
	"axe",
	"bagslots",
	"bakedclay",
	"bed",
	"bendy",
	"bone",
	"book",
	"bouncy",
	"bread_dough",
	"bush",
	"carpet",
	"catchable",
	"cavechest",
	"chainlinks",
	"choppy",
	"coal",
	"color_black",
	"color_blue",
	"color_brown",
	"color_cyan",
	"color_dark_green",
	"color_dark_grey",
	"color_green",
	"color_grey",
	"color_magenta",
	"color_orange",
	"color_pink",
	"color_red",
	"color_violet",
	"color_white",
	"color_yellow",
	"concrete",
	"concrete_post",
	"connect_to_raillike",
	"cools_lava",
	"cracky",
	"crumbly",
	"desert",
	"detector_rail",
	"dig_immediate",
	"digiline_receiver",
	"disable_jump",
	"disable_repair",
	"disable_suffocation",
	"display_api",
	"dl_bc",
	"dl_pp",
	"door",
	"drink",
	"dry_grass",
	"dye",
	"eatable",
	"elevator",
	"explody",
	"fall_damage_add_percent",
	"falling_node",
	"feather",
	"fence",
	"fern",
	"field",
	"fire",
	"flammable",
	"fleshy",
	"flora",
	"flora_block",
	"flow_through",
	"flower",
	"food",
	"food_apple",
	"food_baking_tray",
	"food_banana",
	"food_barberries",
	"food_barley",
	"food_beans",
	"food_beetroot",
	"food_berry",
	"food_bird",
	"food_blackberries",
	"food_blackberry",
	"food_blueberries",
	"food_blueberry",
	"food_bowl",
	"food_bread",
	"food_bread_slice",
	"food_butter",
	"food_cabbage",
	"food_carrot",
	"food_cheese",
	"food_chicken",
	"food_chicken_raw",
	"food_chili_pepper",
	"food_cocoa",
	"food_coffee",
	"food_corn",
	"food_corn_cooked",
	"food_cornstarch",
	"food_cucumber",
	"food_cutting_board",
	"food_egg",
	"food_egg_fried",
	"food_fish",
	"food_flour",
	"food_fruit",
	"food_garlic",
	"food_garlic_clove",
	"food_gelatin",
	"food_gooseberry",
	"food_grapes",
	"food_honey",
	"food_juicer",
	"food_lemon",
	"food_lettuce",
	"food_meat",
	"food_meat_raw",
	"food_melon",
	"food_melon_slice",
	"food_milk",
	"food_milk_glass",
	"food_mint",
	"food_mixing_bowl",
	"food_mortar_pestle",
	"food_mushroom",
	"food_mutton",
	"food_mutton_raw",
	"food_oats",
	"food_oil",
	"food_onion",
	"food_orange",
	"food_pasta",
	"food_pea_pod",
	"food_peas",
	"food_pepper",
	"food_pepper_ground",
	"food_peppercorn",
	"food_pineapple",
	"food_pineapple_ring",
	"food_plate",
	"food_poison",
	"food_pork",
	"food_pork_raw",
	"food_pot",
	"food_potato",
	"food_pumpkin",
	"food_pumpkin_slice",
	"food_rabbit",
	"food_rabbit_raw",
	"food_raspberries",
	"food_raspberry",
	"food_rat",
	"food_rhubarb",
	"food_rice",
	"food_rice_bread",
	"food_rice_flour",
	"food_rice_raw",
	"food_rose_water",
	"food_rye",
	"food_salt",
	"food_sauce",
	"food_saucepan",
	"food_skillet",
	"food_soup",
	"food_soy",
	"food_soy_pod",
	"food_starch",
	"food_strawberry",
	"food_sugar",
	"food_sweet",
	"food_toast",
	"food_tofu",
	"food_tomato",
	"food_tomato_sauce",
	"food_vanilla",
	"food_vegan",
	"food_vinegarmother",
	"food_wheat",
	"fuel",
	"glue",
	"grass",
	"grassland",
	"growing",
	"handy",
	"hay",
	"hoe",
	"horsetail",
	"hot",
	"igniter",
	"ingot",
	"instrument",
	"junglegrass",
	"key",
	"large_banner",
	"lava",
	"leafdecay",
	"leafdecay_drop",
	"leather",
	"leaves",
	"level",
	"liquid",
	"lump",
	"marble",
	"marram_grass",
	"melty",
	"mesecon",
	"mesecon_conductor_craftable",
	"mesecon_effector_off",
	"mesecon_effector_on",
	"mesecon_needs_receiver",
	"mesecon_receptor_off",
	"minegeld",
	"minegeld_coin",
	"minegeld_note",
	"moretrees_coconut",
	"moretrees_dates",
	"moretrees_leaves",
	"mounted_ceiling",
	"mushroom",
	"nametag",
	"node",
	"normal_grass",
	"not_blocking_trains",
	"not_in_craft_guide",
	"not_in_creative_inventory",
	"nsspf_dirt",
	"nsspf_mushroom",
	"oddly_breakable_by_hand",
	"overheat",
	"pane",
	"pebble",
	"pelt",
	"physics_gravity",
	"physics_jump",
	"physics_speed",
	"pickaxe",
	"pizza_dough",
	"plant",
	"poisonivy",
	"potting_soil",
	"puts_out_fire",
	"radioactive",
	"rail",
	"rope",
	"rope_block",
	"saddle",
	"sand",
	"sapling",
	"schema",
	"seafood",
	"seed",
	"seed_flax",
	"seed_lettuce",
	"seed_peanut",
	"seed_soy",
	"shovel",
	"slab",
	"slippery",
	"snappy",
	"snowy",
	"soil",
	"spawn_egg",
	"spreading_dirt_type",
	"stair",
	"stick",
	"stone",
	"string",
	"strip",
	"sud",
	"sword",
	"tar_block",
	"terumet_hline",
	"terumet_hltarget",
	"tnt",
	"tool",
	"torch",
	"travelnet",
	"tree",
	"tubedevice",
	"tubedevice_receiver",
	"ud_param2_colorable",
	"unbreakable",
	"uranium_block",
	"uranium_ingot",
	"vertical_digiline",
	"vessel",
	"vines",
	"wall",
	"water",
	"water_bucket",
	"wet",
	"wire",
	"wood",
	"wool"
}
]]


--[[
-- Generate list of groups and existing images
minetest.register_on_mods_loaded(function ()
	minetest.after(10, function()
		local grs = {}
		for _, group in ipairs(all_groups) do
			table.insert(grs, {
				group=group,
				item=unified_inventory.get_group_item(group).item
			})
		end
		local str = ""
		for _,gd in ipairs(grs) do
			if gd.item then
				str = str..gd.group..' = "',..gd.item..'"'.."\n"
			end
		end
		minetest.log("error", str)
	end)
end)
]]