name: luacheck

on: [push, pull_request]

jobs:
  luacheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run luacheck
      uses: Roang-zero1/factorio-mod-luacheck@master
      with:
        luacheckrc_url: https://raw.githubusercontent.com/BlockySurvival/bls_custom/master/.luacheckrc
